
windowrule = immediate on, content game, match:tag game
windowrule = float on, center on,size 1900 1046, tag +game, match:tag float_game

windowrule = tag +game, match:class ^(steam_app.*)$
windowrule = tag +game,  match:class ^(gamescope)$

# MateEngineX
windowrule = tag +game, match:class ^(MateEngineX.x86_64)$
windowrule = pin on, float on, match:class ^(MateEngineX.x86_64)$
windowrule = size 885 580, match:class ^(MateEngineX.x86_64)$
windowrule = move 3735 860, match:class ^(MateEngineX.x86_64)$
windowrule = opacity 0.9 0.9 1, match:class ^(MateEngineX.x86_64)$

# Chill with you
windowrule = tag +float_game, match:title ^(Chill With You)$
