#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃
#  ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛
#                  


# Print a new line at the start of the prompt
add_newline = true

# Format of the status
format = """
$os $cmd_duration $directory $git_branch $git_status
$character
"""

#--------os-----------#
#---------------------#
[os]
style = 'bg:bright-black fg:yellow'
format = '[](bold fg:bright-black)[$symbol]($style)[](bold fg:bright-black)'
disabled = false

[os.symbols]
Arch = "󰣇 "
EndeavourOS = " "

#-------character--------#
#------------------------#
[character]
success_symbol = "[   ](bold fg:blue)"
error_symbol = "[   ](bold fg:red)"
vimcmd_symbol = "[   ](bold fg:yellow)"
vimcmd_visual_symbol = "[   ](bold fg:yellow)"
vimcmd_replace_symbol = "[   ](bold fg:purple)"
vimcmd_replace_one_symbol = "[   ](bold fg:purple)"
#------directory---------#
#------------------------#
[directory]
style = 'bg:bright-black fg:white'
truncation_length = 6
truncation_symbol = "../"
format = '[](bold fg:bright-black)[$path]($style)[](bold fg:bright-black)'

#------gitBranch-------#
#----------------------#
[git_branch]
style = 'bg:bright-black'
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = '[](bold fg:bright-black)[$symbol $branch(:$remote_branch)](fg:yellow bg:bright-black)[](bold fg:bright-black)'


#------gitStatus-------#
#----------------------#
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](fg:green)" 
modified = "[${count}+](fg:yellow)" 
deleted =  "[${count}-](fg:red)" 
conflicted =  "[${count}~](fg:red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](fg:blue)" 
staged = "[${count}+](fg:green)" 

#-----cmdDuration------#
#----------------------#
[cmd_duration]
min_time = 0
format = '[](bold fg:bright-black)[󰪢 $duration](bold bg:bright-black fg:red)[](bold fg:bright-black)'
