#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
cwd             = { fg = "green" }
hovered         = { reversed = true }
preview_hovered = { underline = false }
border_symbol   = "│"
border_style    = { fg = "white", bold = true }

[mode]
normal_main = { fg = "black", bg = "yellow", bold = true }
normal_alt  = { fg = "black", bg = "green", bold = true }
select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "gray" }
unset_main  = { bg = "red", bold = true }
unset_alt   = { fg = "red", bg = "gray" }

[status]
overall   = { bg = "darkgray", bold = true }
sep_left  = [ "", "" ]
sep_right = [ "", "" ]

[git]
ignored   = { fg = "darkgray" }
untracked = { fg = "magenta" }
unstaged  = { fg = "yellow" }
staged    = { fg = "green" }
added     = { fg = "green" }
deleted   = { fg = "red" }
updated   = { fg = "yellow" }
