#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_dir_first = true
show_symlink   = true
scrolloff      = 5

[preview]
tab_size      = 2
image_delay   = 30
image_filter  = "triangle"
image_quality = 75

[opener]
edit = [
    { run = "nvim %s", desc = "Neovim", block = true, for = "unix" },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
