#!/usr/bin/env bash
# -----------------------------------------------------
# INIT
# -----------------------------------------------------

# -----------------------------------------------------
# Exports
# -----------------------------------------------------
export EDITOR=nvim
export BROWSER="brave --enable-wayland-ime"
export TERMINAL=kitty
export PATH="$HOME/.local/bin/:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$HOME/.local/share/bin:$PATH"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# pnpm
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/.npmrc"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

# rustup
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# Go
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOPATH/bin"

# mise
eval "$(mise activate bash --shims)"
