#  ┓┏┓┏┏┓┳┓┳┳┓┓ ┏┓
#  ┣┫┗┫┃┃┣┫┃┃┃┃ ┣
#  ┛┗┗┛┣┛┛┗┻┻┛┗┛┗┛
#


general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = remote-desktop.sh --wake
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = remote-desktop.sh --idle-dim
    on-resume = remote-desktop.sh --idle-brightness
}

listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = remote-desktop.sh --idle-off
    on-resume = remote-desktop.sh --wake
}

listener {
    timeout = 1800                                # 30min
    on-timeout = remote-desktop.sh --idle-suspend
}
