#  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┫ ┃ ┃  ┃ ┗┫
#  ┛┗┛┻ ┻  ┻ ┗┛
#


#---------------Configuration---------------#
#-------------------------------------------#
font_size                    12

#---------------common config file---------------#
#------------------------------------------------#
include common.conf
